### PR TITLE
fix PEP8

### PR DESCRIPTION
**Pull request by llazzaro**

### CODE REVIEW

**Comment by g--** [comment]
Thank you for the pull request--I'm sorry for taking so long to look at this!

I'm going to merge it with the latest version I have on the dev repo and re-run the tests.

**Comment by g--** [comment]
Yup, that broke the merge.  Hm.

**Comment by g--** [comment]
it looks like the only conflict preventing the merge is I removed "tests.py".  Do you want to re-base and update the pull request?

**Comment by llazzaro** [comment]
done, I updated my fork to the latest branch.

However tests are failing on the original master branch (without my changes)

```python
File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/leonardolazzaro/.virtualenvs/scheduler/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/leonardolazzaro/.virtualenvs/scheduler/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/leonardolazzaro/.virtualenvs/scheduler/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/leonardolazzaro/.virtualenvs/scheduler/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/leonardolazzaro/.virtualenvs/scheduler/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/leonardolazzaro/workspace/bookkeeper2/swingtix/bookkeeper/models.py", line 4, in <module>
    from .account_api import AccountBase, BookSetBase, ProjectBase
  File "/Users/leonardolazzaro/workspace/bookkeeper2/swingtix/bookkeeper/account_api.py", line 106, in <module>
    class AccountBase(object):
  File "/Users/leonardolazzaro/workspace/bookkeeper2/swingtix/bookkeeper/account_api.py", line 154, in AccountBase
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'
```

**Comment by g--** [comment]
Shoot--try rebasing now!

**Comment by llazzaro** [comment]
done! I had to fix a conflict this time.

**Comment by g--** [comment]
Great!  Thanks for fixing all that!

**Pull request merged**
